server:
  port: 8088

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari: #配置数据库连接池相关配置
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  jackson:
    time-zone: GMT+8


  ## ========================redis单机=====================
#  data:
#    redis:
#      host: 自动主机host
#      port: 自己主机post
#      database: 0


## ========================redis集群=====================
#  data:
#    redis:
#      cluster:
#        max-redirects: 3
#        nodes: 192.168.170.139:6381,192.168.170.139:6382,192.168.170.139:6383,192.168.170.139:6384,192.168.170.139:6385,192.168.170.139:6386
#      lettuce:
#        pool:
#          max-active: 8
#          max-wait: -1ms
#          max-idle: 8
#          min-idle: 0
#        cluster:
#          refresh:
#            adaptive: true  #支持集群拓扑动态感应刷新，自适应拓扑刷新是否使用所有可用的更新
#            period: 2000

#===================lgy=============================
  data:
    redis:
      host: 192.168.213.101
      port: 6379
      database: 0
      password: 123456
#===================lgy=============================

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(配置后可以忽略不配置步骤二)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#配置对象存储服务器MinIO
#自定义参数
minio:
  endpoint: http://192.168.170.139:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: lease


springdoc:
  default-flat-param-object: true